inherit_from: ~/.config/rubocop/config.yml

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

AllCops:
  Exclude:
    - 'bin/*'

# rspec blocks are huge by design
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/ExampleWording:
  Enabled: false

RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

RSpec/NotToNot:
  Enabled: false

# TODO: remove this restriction
RSpec/MultipleMemoizedHelpers:
  Enabled: false