inherit_from: ~/.config/rubocop/config.yml

AllCops:
  Exclude:
    - 'bin/*'

# rspec blocks are huge by design
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
